name: 'coveralls'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular: "1.1.2"
  web_components: "0.12.0+3"
  browser: '>=0.10.0 <0.11.0'

dev_dependencies:
  test: "0.12.4+8"

  # library mock is used so dartium browser will not crash
  mock: "^0.12.0"

transformers:
- angular:
    $exclude: "test/*.*"